#!/bin/bash

NAME="cbp_$1"
shift
EXTRA=$@

FILE="cbp.cpp"

COMPILE="g++ -std=c++20"
OPT="-O3"
FLAGS="-Wall -Wextra -pedantic -Wold-style-cast -Werror -Wno-deprecated-declarations -Wno-mismatched-tags"

set -x

$COMPILE -o $NAME $FILE -lz $OPT $FLAGS $EXTRA 
