#!/bin/bash

FILE=$1
shift
EXTRA=$@

NAME="${FILE%.*}"

if [ "$NAME" == "$FILE" ]; then
    FILE="${FILE}.cpp"
fi

COMPILE="g++-15 -std=c++20"
OPT="-O3"
FLAGS="-Wall -Wextra -pedantic -Wold-style-cast -Werror -Wno-deprecated-declarations -Wno-mismatched-tags"

set -x

$COMPILE -o $NAME $FILE -lz $OPT $FLAGS $EXTRA
